### ISSUE TITLE
picker dollies

### ISSUE THREAD

**Issue by CaitSith2** [GregorSamsanite/nullius#10]
There is an API for [picker dollies](https://github.com/Nexela/PickerDollies) to react to moving items,  and blacklisting others from being moved.

This is an example of something that picker dollies should not be allowed to move.  (I put all the geothermal plants into a nice line, and at the same time started tapping that spot for volcanic gas.
![image](https://user-images.githubusercontent.com/79097/197794612-bd3bdf9f-2dec-44a9-9f1d-09236866befc.png)

An example of where picker dollies should react to an entity being moved, so that it gets moved in full, collision zone and all.
![image](https://user-images.githubusercontent.com/79097/197796138-0342cd38-7a7d-4bc3-bb39-9cd6eb042f43.png)

Speaking of collision zones, picker dollies is not even able to move large beacons period, because of it being one Large collision zone rather than 4 separate collision zones that the wind turbines seem to follow.

**Comment by GregorSamsanite** [comment]
This is not currently on the list of supported mods, so this isn't surprising.  However, I've identified the small list of scripted composite buildings and will use the interface to mark them as not moveable.  It's not quite as good as using the other interface to support moving wind turbines and such, but it's a much, much simpler change.  This will be addressed in the next update.

**Comment by GregorSamsanite** [comment]
The current update now prevents moving the small number of problematic scripted buildings.
