### ISSUE TITLE
Adjust stack sizes for SE mod

### ISSUE THREAD

**Issue by macintacos** [GregorSamsanite/nullius#13]
Hello! I'm not sure if bug reports should actually be going here, so I'm duplicating the request from [here](https://mods.factorio.com/mod/safefill/discussion/635ed19e6cbb8ced96f03939) just in case it just wasn't seen. Copying/pasting it below.

> [...] I'm trying out Space Exploration for the first time, and every time I load my save it warns me about stack sizes for items in this mod. I like this mod, so I would like to continue using it without being nagged by this alert every time I start. Any chance you could put in an option to lower the size of stacks for this mod, or perhaps allow it to be "aware" that the user is running SE and lower the stack sizes automatically?
> 
> Below is the full warning I see when I start up:
> 
> ```
> There are 6 items that exceed the recommended stack size.
> 
> Cross-surface logistics are designed for stack sizes around 10-200. The cost of transporting materials between surfaces is a core part of Space Exploration gameplay.
> 
> If a mod has changed stack sizes, consider removing it, otherwise you may have unbalanced logistic costs.
> 
> List of oversized item stacks:
> 
> Shallow waterfill: 500 (Recomennded: 200), Mediumwaterfill: 500 (Recomennded: 200), Deepwaterfill: 500 (Recomennded: 200), Mud waterfill: 500 (Recomennded: 200), Green waterfill: 500 (Recomennded: 200), Deep green waterfill: 500 (Recomennded: 200)
> ```
> 
> Thanks!

**Comment by GregorSamsanite** [comment]
This is resolved in the latest update.
