### ISSUE TITLE
[Nullius] Mini Trains compatibility

### ISSUE THREAD

**Issue by ChristofFritz** [GregorSamsanite/nullius#23]
Hi. 
First of all: Great mod! I love playing it and after 70 hours I finally have construction bots :D 

One mod I'd love to use is [Mini Trains by klonan](https://mods.factorio.com/mod/Mini_Trains). I think this would be a nice addition. I installed the mod but it's not showing up. (I didn't expect for it to work flawlessly tbh).

Can you make it compatible? Or does klonan have to modify their mod?

**Comment by GregorSamsanite** [comment]
Mods can be supported on either end.  See the FAQ tab on the mod portal.  In this case it's one that I was planning to do at some point anyway, and the latest update now supports it.
