### ISSUE TITLE
No long handed inserters

### ISSUE THREAD

**Issue by DeadlyKitten37** [GregorSamsanite/nullius#7]
There are no long inserters, the FAQ states there should be a way to extend a normal inserter into a long inserter. I have tested in both my main save and in sandbox mode and found no way to do this.

the description in the mod portal and the existence of the extension research make me think that this is supposed to be used with the Bob's Adjustable Inserters mod. This mod is not required (Bob's logistics only has it as an optional dependency)

Edit: i just loaded it with Bob's Adjustable Inserters and found that the extension tech does what i expect with the mod installed

pic of GUI
![image](https://user-images.githubusercontent.com/53106272/174092768-a90ad6c8-78ac-4464-b71e-075d1bd1f410.png)

**Comment by GregorSamsanite** [comment]
I believe this was clarified in the Discord.  This extension tech is implemented by the required Bob's logistics mod.  The optional Bob's adjustable inserters mod adds a bunch more configuration options besides just long or regular.  When you research extension, you get an icon in the upper left that can be used to open a gui that lets you select long inserters.  There is also a hot key, which is configurable in the Bob's logistics section of the controls menu.  A confounding factor is that a long inserter must be plugged into the electric grid to extend to its full length.  So if you have no power you might have a long inserter and not know it.
