### ISSUE TITLE
Time to remove basic buildings is really high

### ISSUE THREAD

**Issue by EdwardCooke** [GregorSamsanite/nullius#9]
The latest change to increase deconstruction time has been pretty large on things like belts and pipes. Is there a way we can reduce that?

**Comment by GregorSamsanite** [comment]
Yes, it can be reduced using mining equipment, multi-tool, or high tier telekinesis equipment.  Equipment can give large bonuses to mining speed for very little energy.  A recent update clarifies the description of mining equipment to make it more clear that mining speed applies to building deconstruction.  The next update will slightly bump up the bonus from mining equipment, though it's already quite large. 

This does increase competition for different types of equipment in your equipment grid, however when the new equipment was first released a couple of months ago in 1.5.x, it also came with greatly expanding the size of equipment grids in armor, as well as generators taking up less space for energy than solar panels, so even with mining equipment there is still more space than before.

The other alternative of course is bots, which is not as convenient for small individual buildings, but probably the right choice for a group of belts, pipes.  Though with some mining equipment you can get mining speeds on pipes/belts back to where it was before if you want.

A third option is that I am adding better support for the Picker Dollies mod.  Which isn't so great for pipes an belts, but if you want a building moved 1 or tiles over while you're designing something it may be quicker than mining it and placing it again.

**Comment by GregorSamsanite** [comment]
The current update includes a minor buff to mining equipment, shifts the passive mining bonuses a bit more toward earlier techs, and clarifies what this tech bonus does in the description.

**Comment by GregorSamsanite** [comment]
It's only tangentially related, but the update also boosts running speed equipment, which should help free up a little space in the equipment grid that can be used for mining tools.

**Comment by EdwardCooke** [comment]
Thank you for the replies. We’ll be adding the passive mining tool to our inventory. One suggestion, with the need to add additional items to the inventory at early/mid game (we’re early green research) it would be nice to have a larger inventory.
